Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  config.vm.define "hongbakiS" do |server|
    server.vm.hostname = "hongbakiS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "hongbakiS-p2"
      vb.memory = 2048
      vb.cpus = 1
    end

    server.vm.provision "shell", path: "scripts/server.sh"
  end

end
