Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  config.vm.define "vmS" do |server|
    server.vm.hostname = "vmS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "vmS-p2"
      vb.memory = 1024
      vb.cpus = 1
    end

    server.vm.provision "shell", path: "server.sh"
  end

end
